version: '2'                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                             
services:

  postgis:                                                                                                                                                                                                                                  
    image: gmouchakis/postgis                                                                                                                                                                                         

